name: CodeQL Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2  # 用于获取源代码
    
    # 2. Set up CodeQL
    - name: Set up CodeQL
      uses: github/codeql-action/setup-codeql@v2  # 设置 CodeQL 分析环境

    # 3. Initialize CodeQL database
    - name: Initialize CodeQL database
      run: |
        mkdir -p codeql-database
        codeql database create codeql-database --language=python  # 创建 CodeQL 数据库，指定语言为 Python

    # 4. Run CodeQL analysis
    - name: Run CodeQL analysis
      run: |
        codeql analyze codeql-database --format=sarif --output=python.sarif  # 执行代码扫描并生成 SARIF 格式报告

    # 5. Upload the SARIF results to GitHub
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v2  # 上传扫描结果到 GitHub
      with:
        sarif_file: python.sarif  # 指定 SARIF 文件路径

    # 6. Print a message after the scan is completed
    - name: CodeQL scan completed
      run: echo "CodeQL scan completed."  # 扫描完成后输出信息

